apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: jft-demo-k8s-operator-sdk-0001
    app.kubernetes.io/part-of: jft-demo-k8s-operator-sdk-0001
    app.kubernetes.io/managed-by: kustomize
  name: jftdemooperatorsdks-controller-manager
  namespace: jftdemooperatorsdks
