apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: jft-demo-k8s-operator-sdk-0001
    app.kubernetes.io/part-of: jft-demo-k8s-operator-sdk-0001
    app.kubernetes.io/managed-by: kustomize
  name: jftdemooperatorsdks-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jftdemooperatorsdks-manager-role
subjects:
- kind: ServiceAccount
  name: jftdemooperatorsdks-controller-manager
  namespace: jftdemooperatorsdks
